version: '3.8'

services:
  app:
    image: node:18
    working_dir: /web
    volumes:
      - ./web:/web
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    command: >
      sh -c "yarn install && yarn run dev"
    depends_on:
      - api

  api:
    image: golang:1.22
    working_dir: /go/src/app
    volumes:
      - ./api:/go/src/app
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    command: >
      sh -c "go mod download && bin/run"